version: "3.9"

services:
  poker_mongo:
    container_name: poker_mongo
    image: mongo:latest
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
