name: deploy poker-server by ZUNO
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: supnobita/ssh-action@master
        with:
          host: 175.41.154.239
          username: ubuntu
          key: ${{ secrets.POKER_SECRET }}
          port: 22
          envs: GITHUB_RUN_NUMBER
          script: |
            cd code/
            rm -rf poker-server/
            git clone https://${{ secrets.POKER_TOKEN_SSH }}@github.com/zuno90/poker-server.git
            cd poker-server/
            DOCKER_BUILDKIT=1 docker build -t poker-server:$GITHUB_RUN_NUMBER .
            docker stop poker-server || echo "stop docker OK"
            docker rm poker-server || echo "remove OK"
            docker run -d --restart unless-stopped --name poker-server -p 9000:9000 \
                -e NODE_ENV=production \
                -e HOST=172.31.31.206 \
                -e WS_SERVER=${{ secrets.WS_SERVER }} \
                -e REDIS_URL=${{ secrets.REDIS_URL }} \
                -e MONGO_URI=${{ secrets.MONGO_URI }} \
                -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
                -e MONGO_PORT=${{ secrets.MONGO_PORT }} \
                -e MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
                -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
                -e MONGO_DATABASE_NAME=${{ secrets.MONGO_DATABASE_NAME }} \
                -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                poker-server:$GITHUB_RUN_NUMBER
