name: build and push poker-server
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create test-builder
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: test-builder
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: 327206169735.dkr.ecr.ap-southeast-1.amazonaws.com
          username: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
      - name: Build and push
        id: pushimage
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            327206169735.dkr.ecr.ap-southeast-1.amazonaws.com/poker:poker-server-${{ github.run_number }}
          file: Dockerfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      # --- #
      - name: Deploy container
        uses: ianbelcher/eks-kubectl-action@master
        with:
          cluster_name: k8s-dev
          args: set image --record deployment/poker-server poker-server=327206169735.dkr.ecr.ap-southeast-1.amazonaws.com/poker:poker-server-${{ github.run_number }}
